/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mysqlörnek;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author MFİ
 */
public class UpdateFrameBody extends javax.swing.JFrame {

    /**
     * Creates new form UpdateFrameBody
     */
    public UpdateFrameBody() {
        initComponents();
        ıcons();

    }
     public void ıcons(){
    Icon Btn_updateIcon = new ImageIcon("C:\\Users\\MFİ\\Documents\\NetBeansProjects\\mysqlörnek\\src\\change.png");
     Btn_Update.setIcon(Btn_updateIcon);
     Icon Btn_backIcon = new ImageIcon("C:\\Users\\MFİ\\Documents\\NetBeansProjects\\mysqlörnek\\src\\back.png");
     Btn_Back.setIcon(Btn_backIcon);
      Icon Btn_showIcon = new ImageIcon("C:\\Users\\MFİ\\Documents\\NetBeansProjects\\mysqlörnek\\src\\show2.png");
     Btn_Show.setIcon(Btn_showIcon);
     
}

    public Connection getConnection() {
        Connection con = null;
        String url = "jdbc:mysql://localhost:3306/uygulamam";
        String kök = "root";
        String şifre = "*****";
        try {
            con = DriverManager.getConnection(url, kök, şifre);
            //                               uzantısı      localhost/veritabanı ismi,kullanıcı adı sanırım 
            //veritabanına buradn erişim sağlıyoruz aşşağıda da tabloya direkt gönderiiyoruz (veritabanı içindeki)
            //bağlantıyı libraries den add library ekleyerek sağladım (kütüphane ekledim)
            return con;
        } catch (SQLException ex) {
            Logger.getLogger(MAİN.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Not Connected");
            return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_ID = new javax.swing.JTextField();
        Age3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_Biceps = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_Breast = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_Waists = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_Calf_and_Leg = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_Neck = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_Shoulder = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_Hip = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_Wrist = new javax.swing.JTextField();
        txt_OP = new javax.swing.JLabel();
        txt_Oil_Percetage = new javax.swing.JTextField();
        txt_MH = new javax.swing.JLabel();
        txt_Muscle_Weight = new javax.swing.JTextField();
        Btn_Update = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_Weight = new javax.swing.JTextField();
        txt_Length = new javax.swing.JTextField();
        Btn_Back = new javax.swing.JButton();
        txt_Bicepsup = new javax.swing.JTextField();
        txt_Breastup = new javax.swing.JTextField();
        txt_Waistsup = new javax.swing.JTextField();
        txt_Calf_and_Legup = new javax.swing.JTextField();
        txt_Neckup = new javax.swing.JTextField();
        txt_Shoulderup = new javax.swing.JTextField();
        txt_Hipup = new javax.swing.JTextField();
        txt_Wristup = new javax.swing.JTextField();
        txt_Oil_Percetageup = new javax.swing.JTextField();
        txt_Muscle_Weightup = new javax.swing.JTextField();
        txt_Weightup = new javax.swing.JTextField();
        txt_Lengthup = new javax.swing.JTextField();
        Btn_Show = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setPreferredSize(new java.awt.Dimension(1100, 600));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setText("ID:");

        txt_ID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_IDActionPerformed(evt);
            }
        });

        Age3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Biceps(cm)");

        txt_Biceps.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Biceps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_BicepsActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Breast(cm)");

        txt_Breast.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Waist(cm)");

        txt_Waists.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Calf and Leg(cm)");

        txt_Calf_and_Leg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Calf_and_Leg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Calf_and_LegActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Neck(cm)");

        txt_Neck.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Shoulder(cm)");

        txt_Shoulder.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Shoulder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ShoulderActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("      Hip(cm)");

        txt_Hip.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText(" Wrist(cm)");

        txt_Wrist.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Wrist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_WristActionPerformed(evt);
            }
        });

        txt_OP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_OP.setText(" Oil Percentage (%)");

        txt_Oil_Percetage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Oil_Percetage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Oil_PercetageActionPerformed(evt);
            }
        });

        txt_MH.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_MH.setText(" Muscle Weight(kg)");

        txt_Muscle_Weight.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Muscle_Weight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Muscle_WeightActionPerformed(evt);
            }
        });

        Btn_Update.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Btn_Update.setText("Update");
        Btn_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_UpdateActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("Body Measure Information");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Weight(kg)");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Length(cm)");

        txt_Weight.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Weight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_WeightActionPerformed(evt);
            }
        });

        txt_Length.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Length.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_LengthActionPerformed(evt);
            }
        });

        Btn_Back.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Btn_Back.setText("Back");
        Btn_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_BackActionPerformed(evt);
            }
        });

        txt_Bicepsup.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Bicepsup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_BicepsupActionPerformed(evt);
            }
        });

        txt_Breastup.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txt_Waistsup.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txt_Calf_and_Legup.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Calf_and_Legup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Calf_and_LegupActionPerformed(evt);
            }
        });

        txt_Neckup.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txt_Shoulderup.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Shoulderup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ShoulderupActionPerformed(evt);
            }
        });

        txt_Hipup.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txt_Wristup.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Wristup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_WristupActionPerformed(evt);
            }
        });

        txt_Oil_Percetageup.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Oil_Percetageup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Oil_PercetageupActionPerformed(evt);
            }
        });

        txt_Muscle_Weightup.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Muscle_Weightup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Muscle_WeightupActionPerformed(evt);
            }
        });

        txt_Weightup.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Weightup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_WeightupActionPerformed(evt);
            }
        });

        txt_Lengthup.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_Lengthup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_LengthupActionPerformed(evt);
            }
        });

        Btn_Show.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Btn_Show.setText("Show");
        Btn_Show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ShowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Age3)
                        .addGap(727, 727, 727))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(txt_Wrist, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel10))
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addGap(4, 4, 4)
                                                        .addComponent(jLabel5)))
                                                .addGap(50, 50, 50)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(txt_Breast, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(txt_Breastup, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(txt_Biceps, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(txt_Bicepsup, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(43, 43, 43)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txt_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel7)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addGap(4, 4, 4)
                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jLabel9))))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(4, 4, 4)
                                                                .addComponent(txt_Waists, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addComponent(txt_Shoulder, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(txt_Neck, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(18, 18, 18)
                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(txt_Calf_and_Legup, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(txt_Waistsup, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(txt_Neckup, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(txt_Shoulderup, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addComponent(txt_Calf_and_Leg, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addComponent(Btn_Back))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 30, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addGap(40, 40, 40)
                                                .addComponent(txt_Hip, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel15)
                                                    .addComponent(txt_OP)
                                                    .addComponent(txt_MH, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(12, 12, 12)))
                                                .addGap(31, 31, 31)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txt_Oil_Percetage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txt_Muscle_Weight, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txt_Weight, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txt_Length, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(Btn_Show, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Wristup, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Hipup, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Oil_Percetageup, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Muscle_Weightup, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Weightup, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Lengthup, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(214, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Btn_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(Age3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Btn_Back)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Btn_Show, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Biceps, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Hip, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Bicepsup, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Hipup, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Breast, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Wrist, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Breastup, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Wristup, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Waists, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_OP, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Oil_Percetage, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Waistsup, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Oil_Percetageup, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Calf_and_Leg, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Calf_and_Legup, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_MH, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Muscle_Weight, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Muscle_Weightup, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_Neckup, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_Weight, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_Weightup, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_Neck, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Shoulder, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Shoulderup, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Length, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Lengthup, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_IDActionPerformed

    private void txt_BicepsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_BicepsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_BicepsActionPerformed

    private void txt_Calf_and_LegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Calf_and_LegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Calf_and_LegActionPerformed

    private void txt_ShoulderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ShoulderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ShoulderActionPerformed

    private void txt_WristActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_WristActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_WristActionPerformed

    private void txt_Oil_PercetageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Oil_PercetageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Oil_PercetageActionPerformed

    private void txt_Muscle_WeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Muscle_WeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Muscle_WeightActionPerformed

    private void Btn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_UpdateActionPerformed
       LoginPage lp = new LoginPage();
        if (txt_ID.getText() != null) {

            Connection con = getConnection();
            try {
                PreparedStatement ps = con.prepareStatement("UPDATE body_measurements SET Weight=?,Length=?,Biceps=?,Breast=?,Waists=? , "
                        + "Calf_and_Leg=?,Neck=?,Shoulder=?,Hip=?,Wrist=?,Oil_Percentage=?,Muscle_Weight=?  WHERE ID=?");

                //PS.SET... KISMINAN SEÇEREK GÖNDERİYORUZ
                ps.setString(1, txt_Bicepsup.getText());

                ps.setString(2, txt_Weightup.getText());

                ps.setString(3, txt_Lengthup.getText());

                ps.setString(4, txt_Breastup.getText());

                ps.setString(5, txt_Calf_and_Legup.getText());

                ps.setString(6, txt_Hipup.getText());

                ps.setString(7, txt_Neckup.getText());

                ps.setString(8, txt_Shoulderup.getText());

                ps.setString(9, txt_Waistsup.getText());

                ps.setString(10, txt_Wristup.getText());

                ps.setString(11, txt_Oil_Percetageup.getText());

                ps.setString(12, txt_Muscle_Weightup.getText());

                ps.setString(13, txt_ID.getText());

                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Update");

                setVisible(false);
                lp.setVisible(true);

            } catch (SQLException ex) {
                Logger.getLogger(UpdateFrameBody.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }

        }
    }//GEN-LAST:event_Btn_UpdateActionPerformed

    private void txt_WeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_WeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_WeightActionPerformed

    private void txt_LengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_LengthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_LengthActionPerformed

    private void Btn_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_BackActionPerformed
        LoginPage lp = new LoginPage();

        setVisible(false);
        lp.setVisible(true);
    }//GEN-LAST:event_Btn_BackActionPerformed

    private void txt_BicepsupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_BicepsupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_BicepsupActionPerformed

    private void txt_Calf_and_LegupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Calf_and_LegupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Calf_and_LegupActionPerformed

    private void txt_ShoulderupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ShoulderupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ShoulderupActionPerformed

    private void txt_WristupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_WristupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_WristupActionPerformed

    private void txt_Oil_PercetageupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Oil_PercetageupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Oil_PercetageupActionPerformed

    private void txt_Muscle_WeightupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Muscle_WeightupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Muscle_WeightupActionPerformed

    private void txt_WeightupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_WeightupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_WeightupActionPerformed

    private void txt_LengthupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_LengthupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_LengthupActionPerformed

    private void Btn_ShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ShowActionPerformed

        Connection con = getConnection();

        try {
            Object ID = txt_ID.getText();
            String querybody = "SELECT * FROM body_measurements Where ID=" + ID;

            Statement st2 = con.createStatement();
            ResultSet rs2 = st2.executeQuery(querybody);

            while (rs2.next()) {
                txt_Weight.setText(rs2.getString("Weight"));

                txt_Length.setText(rs2.getString("Length"));

                txt_Biceps.setText(rs2.getString("Weight"));

                txt_Breast.setText(rs2.getString("Breast"));

                txt_Waists.setText(rs2.getString("Waists"));

                txt_Calf_and_Leg.setText(rs2.getString("Calf_and_Leg"));

                txt_Neck.setText(rs2.getString("Neck"));

                txt_Shoulder.setText(rs2.getString("Shoulder"));

                txt_Hip.setText(rs2.getString("Hip"));

                txt_Wrist.setText(rs2.getString("Wrist"));

                txt_Oil_Percetage.setText(rs2.getString("Oil_Percentage"));

                txt_Muscle_Weight.setText(rs2.getString("Muscle_Weight"));

            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_Btn_ShowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateFrameBody.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateFrameBody.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateFrameBody.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateFrameBody.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateFrameBody().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Age3;
    private javax.swing.JButton Btn_Back;
    private javax.swing.JButton Btn_Show;
    private javax.swing.JButton Btn_Update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txt_Biceps;
    private javax.swing.JTextField txt_Bicepsup;
    private javax.swing.JTextField txt_Breast;
    private javax.swing.JTextField txt_Breastup;
    private javax.swing.JTextField txt_Calf_and_Leg;
    private javax.swing.JTextField txt_Calf_and_Legup;
    private javax.swing.JTextField txt_Hip;
    private javax.swing.JTextField txt_Hipup;
    private javax.swing.JTextField txt_ID;
    private javax.swing.JTextField txt_Length;
    private javax.swing.JTextField txt_Lengthup;
    private javax.swing.JLabel txt_MH;
    private javax.swing.JTextField txt_Muscle_Weight;
    private javax.swing.JTextField txt_Muscle_Weightup;
    private javax.swing.JTextField txt_Neck;
    private javax.swing.JTextField txt_Neckup;
    private javax.swing.JLabel txt_OP;
    private javax.swing.JTextField txt_Oil_Percetage;
    private javax.swing.JTextField txt_Oil_Percetageup;
    private javax.swing.JTextField txt_Shoulder;
    private javax.swing.JTextField txt_Shoulderup;
    private javax.swing.JTextField txt_Waists;
    private javax.swing.JTextField txt_Waistsup;
    private javax.swing.JTextField txt_Weight;
    private javax.swing.JTextField txt_Weightup;
    private javax.swing.JTextField txt_Wrist;
    private javax.swing.JTextField txt_Wristup;
    // End of variables declaration//GEN-END:variables
}
